from time import sleep
def Verse1():
  print("We're no strangers to love")
  sleep(3)
  print("You know the rules, and so do I")
  sleep(3)
  print("I feel commitment's what I'm thinking of")
  sleep(3)
  print("You wouldn't get this from any other guy")
  sleep(3)
  print("I just wanna tell you how I'm feeling")
  sleep(3)
  print("Gotta make you, understand")
  sleep(3)
def Chorus():
  print("Never gonna give you up")
  sleep(3)
  print("Never gonna let you down")
  sleep(3)
  print("Never gonna run around and, desert you")
  sleep(3)
  print("Never gonna make you cry")
  sleep(3)
  print("Never gonna say goodbye")
  sleep(3)
  print("Never gonna tell a lie and hurt you")
  sleep(3)
def Verse2():
  print("We've known each other for so long")
  sleep(3)
  print("Your heart's been aching but you're too shy to say it")
  sleep(3)
  print("Inside we both know what's been going on")
  sleep(3)
  print("We know the game and we're gonna play it")
  sleep(3)
  print("And if you ask me how I'm feeling")
  sleep(3)
  print("Don't tell me you're too blind to see")
  sleep(3)
def InterVerse():
  print("Never gonna give, never gonna give")
  print("(Give you up)")
  sleep(2)
  print("(Ooh) Never gonna give, never gonna give")
  print("(Give you up)")
  sleep(2)
Verse1()
Chorus()
Verse2()
Chorus()
Chorus()
InterVerse()
Verse2()
Chorus()
Chorus()
Chorus()